<?php
/**
* Zebra Enhance [Persian]
*
* @copyright (c) 2013-2026 Stanislav Atanasov
* @copyright (c) 2026 Leinad4Mind
* @license GNU General Public License, version 2 (GPL-2.0-only)
*/
if (!defined('IN_PHPBB'))
{
	exit;
}
if (empty($lang) || !is_array($lang))
{
	$lang = array();
}
$lang = array_merge($lang, array(
	'ACP_ZEBRA_ENHANCE_TITLE' => 'Zebra Enhance',
	'ACP_ZEBRA_ENHANCE_SETTINGS' => 'تنظیمات درخواست دوستی',
	'ACP_ZEBRA_ENHANCE_SETTINGS_EXPLAIN' => 'محدودیت‌های عمومی درخواست دوستی را تنظیم کنید. هر کاربر می‌تواند در کنترل پنل محدودیت بیشتری انتخاب کند.',
	'ACP_ZEBRA_ENHANCE_REQUESTS' => 'محدودیت درخواست‌ها',
	'ACP_ZE_MAX_PENDING_REQUESTS' => 'حداکثر درخواست‌های در انتظار',
	'ACP_ZE_MAX_PENDING_REQUESTS_EXPLAIN' => 'حداکثر درخواست‌های ورودی و خروجی هر کاربر که برای هر جهت جداگانه اعمال می‌شود. مقدار ۰ یعنی بدون محدودیت.',
	'ACP_ZE_DECLINE_COOLDOWN_DAYS' => 'فاصله پس از رد درخواست',
	'ACP_ZE_DECLINE_COOLDOWN_DAYS_EXPLAIN' => 'تعداد روز تا امکان ارسال دوباره درخواست توسط فرد ردشده. مقدار ۰ این گزینه را غیرفعال می‌کند.',
	'ACP_ZEBRA_ENHANCE_SAVED' => 'تنظیمات Zebra Enhance به‌روز شد.',
	'ACP_ZEBRA_ENHANCE_REPORT' => 'Pending friend requests',
	'ACP_ZEBRA_ENHANCE_REPORT_EXPLAIN' => 'Read-only board-wide report of friend requests that have not yet been accepted, declined, or cancelled.',
	'ACP_ZE_REQUEST_ID' => 'Request ID',
	'ACP_ZE_REQUESTER' => 'Requester',
	'ACP_ZE_RECIPIENT' => 'Recipient',
	'ACP_ZE_REQUEST_DATE' => 'Requested',
	'ACP_ZE_REQUEST_MESSAGE' => 'Message',
	'ACP_ZE_NO_PENDING_REQUESTS' => 'There are no pending friend requests.',
	'ACP_ZE_PENDING_TOTAL' => array(1 => '%d pending friend request', 2 => '%d pending friend requests'),
	'LOG_ZEBRA_ENHANCE_SETTINGS' => '<strong>تنظیمات Zebra Enhance تغییر کرد</strong><br>» حداکثر در انتظار: %1$d؛ فاصله رد: %2$d روز; foe enhancements: %3$s',
	'ACP_ZEBRA_ENHANCE_FOES' => 'Foe enhancements',
	'ACP_ZE_FOES_ENHANCEMENT' => 'Enable foe enhancements',
	'ACP_ZE_FOES_ENHANCEMENT_EXPLAIN' => 'Makes the enhanced foe manager and the selected protections below available to users. When disabled, phpBB\'s native foe behaviour remains unchanged.',
	'ACP_ZE_FOE_PM' => 'Private message protection',
	'ACP_ZE_FOE_PM_EXPLAIN' => 'Allow users to reject private messages sent by their foes.',
	'ACP_ZE_FOE_CONTENT' => 'Content and quote hiding',
	'ACP_ZE_FOE_CONTENT_EXPLAIN' => 'Allow users to hide posts, search results, and identifiable quotes from their foes.',
	'ACP_ZE_FOE_NOTIFICATIONS' => 'Notification muting',
	'ACP_ZE_FOE_NOTIFICATIONS_EXPLAIN' => 'Allow users to suppress supported notifications generated by their foes.',
	'ACP_ZE_FOE_TEMPORARY' => 'Temporary foes',
	'ACP_ZE_FOE_TEMPORARY_EXPLAIN' => 'Allow users to make foe relationships expire after 24 hours, 7 days, or 30 days.',
	'ACP_ZE_FOE_NOTES' => 'Private foe notes',
	'ACP_ZE_FOE_NOTES_EXPLAIN' => 'Allow users to store a private note for each foe.',
	'ACP_ZE_FOE_EXCEPTIONS' => 'Per-foe exceptions',
	'ACP_ZE_FOE_EXCEPTIONS_EXPLAIN' => 'Allow users to override their global PM, content, and notification choices for individual foes.',
));
