<?php
/**
* Zebra Enhance [Dutch]
*
* @copyright (c) 2013-2026 Stanislav Atanasov
* @copyright (c) 2026 Leinad4Mind
* @license GNU General Public License, version 2 (GPL-2.0-only)
*/
if (!defined('IN_PHPBB'))
{
	exit;
}
if (empty($lang) || !is_array($lang))
{
	$lang = array();
}
$lang = array_merge($lang, array(
	'ACP_ZEBRA_ENHANCE_TITLE' => 'Zebra Enhance',
	'ACP_ZEBRA_ENHANCE_SETTINGS' => 'Instellingen voor vriendschapsverzoeken',
	'ACP_ZEBRA_ENHANCE_SETTINGS_EXPLAIN' => 'Stel algemene limieten voor vriendschapsverzoeken in. Gebruikers kunnen in het UCP extra beperkingen instellen.',
	'ACP_ZEBRA_ENHANCE_REQUESTS' => 'Verzoeklimieten',
	'ACP_ZEBRAENHANCE_MAX_PENDING_REQUESTS' => 'Maximum openstaande verzoeken',
	'ACP_ZEBRAENHANCE_MAX_PENDING_REQUESTS_EXPLAIN' => 'Maximum aantal ontvangen en verzonden verzoeken per gebruiker, afzonderlijk toegepast per richting. Gebruik 0 voor onbeperkt.',
	'ACP_ZEBRAENHANCE_DECLINE_COOLDOWN_DAYS' => 'Wachttijd na afwijzing',
	'ACP_ZEBRAENHANCE_DECLINE_COOLDOWN_DAYS_EXPLAIN' => 'Dagen voordat een afgewezen persoon opnieuw een verzoek kan sturen. Gebruik 0 om uit te schakelen.',
	'ACP_ZEBRA_ENHANCE_SAVED' => 'Instellingen van Zebra Enhance bijgewerkt.',
	'ACP_ZEBRA_ENHANCE_REPORT' => 'Openstaande vriendschapsverzoeken',
	'ACP_ZEBRA_ENHANCE_REPORT_EXPLAIN' => 'Forum-breed alleen-lezenoverzicht van verzoeken die nog niet zijn geaccepteerd, geweigerd of geannuleerd.',
	'ACP_ZEBRAENHANCE_REQUEST_ID' => 'Verzoek-ID',
	'ACP_ZEBRAENHANCE_REQUESTER' => 'Aanvrager',
	'ACP_ZEBRAENHANCE_RECIPIENT' => 'Ontvanger',
	'ACP_ZEBRAENHANCE_REQUEST_DATE' => 'Aangevraagd',
	'ACP_ZEBRAENHANCE_REQUEST_MESSAGE' => 'Bericht',
	'ACP_ZEBRAENHANCE_NO_PENDING_REQUESTS' => 'Er zijn geen openstaande vriendschapsverzoeken.',
	'ACP_ZEBRAENHANCE_PENDING_TOTAL' => array(1 => '%d openstaand vriendschapsverzoek', 2 => '%d openstaande vriendschapsverzoeken'),
	'LOG_ZEBRA_ENHANCE_SETTINGS' => '<strong>Instellingen van Zebra Enhance gewijzigd</strong><br>» Maximum openstaand: %1$d; wachttijd: %2$d dagen; foe enhancements: %3$s',
	'ACP_ZEBRA_ENHANCE_FOES' => 'Foe enhancements',
	'ACP_ZEBRAENHANCE_FOES_ENHANCEMENT' => 'Enable foe enhancements',
	'ACP_ZEBRAENHANCE_FOES_ENHANCEMENT_EXPLAIN' => 'Makes the enhanced foe manager and the selected protections below available to users. When disabled, phpBB\'s native foe behaviour remains unchanged.',
	'ACP_ZEBRAENHANCE_FOE_PM' => 'Private message protection',
	'ACP_ZEBRAENHANCE_FOE_PM_EXPLAIN' => 'Allow users to reject private messages sent by their foes.',
	'ACP_ZEBRAENHANCE_FOE_CONTENT' => 'Content and quote hiding',
	'ACP_ZEBRAENHANCE_FOE_CONTENT_EXPLAIN' => 'Allow users to hide posts, search results, and identifiable quotes from their foes.',
	'ACP_ZEBRAENHANCE_FOE_NOTIFICATIONS' => 'Notification muting',
	'ACP_ZEBRAENHANCE_FOE_NOTIFICATIONS_EXPLAIN' => 'Allow users to suppress supported notifications generated by their foes.',
	'ACP_ZEBRAENHANCE_FOE_TEMPORARY' => 'Temporary foes',
	'ACP_ZEBRAENHANCE_FOE_TEMPORARY_EXPLAIN' => 'Allow users to make foe relationships expire after 24 hours, 7 days, or 30 days.',
	'ACP_ZEBRAENHANCE_FOE_NOTES' => 'Private foe notes',
	'ACP_ZEBRAENHANCE_FOE_NOTES_EXPLAIN' => 'Allow users to store a private note for each foe.',
	'ACP_ZEBRAENHANCE_FOE_EXCEPTIONS' => 'Per-foe exceptions',
	'ACP_ZEBRAENHANCE_FOE_EXCEPTIONS_EXPLAIN' => 'Allow users to override their global PM, content, and notification choices for individual foes.',
));
