<?php
/**
* Zebra Enhance [Spanish]
*
* @copyright (c) 2013-2026 Stanislav Atanasov
* @copyright (c) 2026 Leinad4Mind
* @license GNU General Public License, version 2 (GPL-2.0-only)
*/
if (!defined('IN_PHPBB'))
{
	exit;
}
if (empty($lang) || !is_array($lang))
{
	$lang = array();
}
$lang = array_merge($lang, array(
	'ACP_ZEBRA_ENHANCE_TITLE' => 'Zebra Enhance',
	'ACP_ZEBRA_ENHANCE_SETTINGS' => 'Ajustes de solicitudes de amistad',
	'ACP_ZEBRA_ENHANCE_SETTINGS_EXPLAIN' => 'Configura los límites globales para las solicitudes. Cada usuario puede aplicar más restricciones en el UCP.',
	'ACP_ZEBRA_ENHANCE_REQUESTS' => 'Límites de solicitudes',
	'ACP_ZEBRAENHANCE_MAX_PENDING_REQUESTS' => 'Máximo de solicitudes pendientes',
	'ACP_ZEBRAENHANCE_MAX_PENDING_REQUESTS_EXPLAIN' => 'Máximo de solicitudes recibidas y enviadas por usuario, aplicado por separado a cada dirección. Usa 0 para no limitar.',
	'ACP_ZEBRAENHANCE_DECLINE_COOLDOWN_DAYS' => 'Espera tras un rechazo',
	'ACP_ZEBRAENHANCE_DECLINE_COOLDOWN_DAYS_EXPLAIN' => 'Días hasta que la persona rechazada pueda enviar otra solicitud. Usa 0 para desactivar.',
	'ACP_ZEBRA_ENHANCE_SAVED' => 'Ajustes de Zebra Enhance actualizados.',
	'ACP_ZEBRA_ENHANCE_REPORT' => 'Solicitudes de amistad pendientes',
	'ACP_ZEBRA_ENHANCE_REPORT_EXPLAIN' => 'Informe global de solo lectura de las solicitudes que aún no se han aceptado, rechazado o cancelado.',
	'ACP_ZEBRAENHANCE_REQUEST_ID' => 'ID de solicitud',
	'ACP_ZEBRAENHANCE_REQUESTER' => 'Solicitante',
	'ACP_ZEBRAENHANCE_RECIPIENT' => 'Destinatario',
	'ACP_ZEBRAENHANCE_REQUEST_DATE' => 'Solicitada',
	'ACP_ZEBRAENHANCE_REQUEST_MESSAGE' => 'Mensaje',
	'ACP_ZEBRAENHANCE_NO_PENDING_REQUESTS' => 'No hay solicitudes de amistad pendientes.',
	'ACP_ZEBRAENHANCE_PENDING_TOTAL' => array(1 => '%d solicitud de amistad pendiente', 2 => '%d solicitudes de amistad pendientes'),
	'LOG_ZEBRA_ENHANCE_SETTINGS' => '<strong>Cambió los ajustes de Zebra Enhance</strong><br>» Máximo pendiente: %1$d; espera tras rechazo: %2$d días; foe enhancements: %3$s',
	'ACP_ZEBRA_ENHANCE_FOES' => 'Foe enhancements',
	'ACP_ZEBRAENHANCE_FOES_ENHANCEMENT' => 'Enable foe enhancements',
	'ACP_ZEBRAENHANCE_FOES_ENHANCEMENT_EXPLAIN' => 'Makes the enhanced foe manager and the selected protections below available to users. When disabled, phpBB\'s native foe behaviour remains unchanged.',
	'ACP_ZEBRAENHANCE_FOE_PM' => 'Private message protection',
	'ACP_ZEBRAENHANCE_FOE_PM_EXPLAIN' => 'Allow users to reject private messages sent by their foes.',
	'ACP_ZEBRAENHANCE_FOE_CONTENT' => 'Content and quote hiding',
	'ACP_ZEBRAENHANCE_FOE_CONTENT_EXPLAIN' => 'Allow users to hide posts, search results, and identifiable quotes from their foes.',
	'ACP_ZEBRAENHANCE_FOE_NOTIFICATIONS' => 'Notification muting',
	'ACP_ZEBRAENHANCE_FOE_NOTIFICATIONS_EXPLAIN' => 'Allow users to suppress supported notifications generated by their foes.',
	'ACP_ZEBRAENHANCE_FOE_TEMPORARY' => 'Temporary foes',
	'ACP_ZEBRAENHANCE_FOE_TEMPORARY_EXPLAIN' => 'Allow users to make foe relationships expire after 24 hours, 7 days, or 30 days.',
	'ACP_ZEBRAENHANCE_FOE_NOTES' => 'Private foe notes',
	'ACP_ZEBRAENHANCE_FOE_NOTES_EXPLAIN' => 'Allow users to store a private note for each foe.',
	'ACP_ZEBRAENHANCE_FOE_EXCEPTIONS' => 'Per-foe exceptions',
	'ACP_ZEBRAENHANCE_FOE_EXCEPTIONS_EXPLAIN' => 'Allow users to override their global PM, content, and notification choices for individual foes.',
));
