anavaro_zebraenhance_close_friend:
    path: /zebraenhance/close-friend/{userid}/{state}
    defaults: { _controller: anavaro.zebraenhance.controller:set_close_friend }
    methods: [POST]
    requirements:
        userid: \d+
        state: 0|1

anavaro_zebraenhance_manage_request:
    path: /zebraenhance/request/{requestid}/{action}
    defaults: { _controller: anavaro.zebraenhance.controller:manage_request }
    methods: [POST]
    requirements:
        requestid: \d+
        action: accept|decline|cancel

anavaro_zebraenhance_create_request:
    path: /zebraenhance/friend/{userid}/request
    defaults: { _controller: anavaro.zebraenhance.controller:create_request }
    methods: [POST]
    requirements:
        userid: \d+

anavaro_zebraenhance_create_circle:
    path: /zebraenhance/circle
    defaults: { _controller: anavaro.zebraenhance.controller:create_circle }
    methods: [POST]

anavaro_zebraenhance_manage_circle:
    path: /zebraenhance/circle/{circleid}/{action}
    defaults: { _controller: anavaro.zebraenhance.controller:manage_circle }
    methods: [POST]
    requirements:
        circleid: \d+
        action: rename|delete

anavaro_zebraenhance_friend_circles:
    path: /zebraenhance/friend/{userid}/circles
    defaults: { _controller: anavaro.zebraenhance.controller:set_friend_circles }
    methods: [POST]
    requirements:
        userid: \d+
