services:
    anavaro.zebraenhance.listener:
        class: anavaro\zebraenhance\event\zebra_listener
        arguments:
            - '@user_loader'
            - '@auth'
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@anavaro.zebraenhance.notifyhelper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
        tags:
            - { name: event.listener }
    anavaro.zebraenhance.ajaxyfy:
        class: anavaro\zebraenhance\controller\ajaxify
        arguments:
            - '@dbal.conn'
            - '@request'
            - '@user'
            - '@language'
            - '%core.root_path%'
            - '%core.table_prefix%'
    anavaro.zebraenhance.notifyhelper:
        class: anavaro\zebraenhance\controller\notifyhelper
        arguments:
            - '@service_container'
    notification.type.zebraadd:
        class: anavaro\zebraenhance\notification\zebraadd
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@user'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notifications%'
        calls:
            - [set_user_loader, [@user_loader]]
            - [set_config, [@config]]
        tags:
            - { name: notification.type }
    
    notification.type.zebraconfirm:
        class: anavaro\zebraenhance\notification\zebraconfirm
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@user'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notifications%'
        calls:
            - [set_user_loader, [@user_loader]]
            - [set_config, [@config]]
        tags:
            - { name: notification.type }