services:
    anavaro.zebraenhance.relationships:
        class: anavaro\zebraenhance\service\relationship_manager
        arguments:
            - '@dbal.conn'
            - '@dbal.tools'
            - '@auth'
            - '@notification_manager'
            - '@dispatcher'
            - '@config'
            - '%core.table_prefix%zebra_requests'
            - '%core.table_prefix%zebra_request_cooldowns'
            - '%core.table_prefix%zebra_confirm'
            - '%core.table_prefix%zebra'
            - '%core.table_prefix%zebra_circles'
            - '%core.table_prefix%zebra_circle_members'
            - '%core.table_prefix%users'
            - '%core.table_prefix%notifications'
            - '%core.table_prefix%notification_emails'
            - '%core.table_prefix%notification_types'

    anavaro.zebraenhance.listener:
        class: anavaro\zebraenhance\event\zebra_listener
        arguments:
            - '@anavaro.zebraenhance.relationships'
            - '@user_loader'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@controller.helper'
            - '@pagination'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    anavaro.zebraenhance.controller:
        class: anavaro\zebraenhance\controller\ajaxify
        arguments:
            - '@anavaro.zebraenhance.relationships'
            - '@auth'
            - '@request'
            - '@user'
            - '@language'

    anavaro.zebraenhance.notification.zebraadd:
        class: anavaro\zebraenhance\notification\zebraadd
        shared: false
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
        tags:
            - { name: notification.type }

    anavaro.zebraenhance.notification.zebraconfirm:
        class: anavaro\zebraenhance\notification\zebraconfirm
        shared: false
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
        tags:
            - { name: notification.type }
