services:
    anavaro.zebraenhance.listener:
        class: anavaro\zebraenhance\event\zebra_listener
        arguments:
            - '@user_loader'
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@anavaro.zebraenhance.notifyhelper'
            - '%core.table_prefix%'
        tags:
            - { name: event.listener }
    anavaro.zebraenhance.ajaxyfy:
        class: anavaro\zebraenhance\controller\ajaxify
        arguments:
            - '@dbal.conn'
            - '@request'
            - '@user'
            - '@language'
            - '%core.root_path%'
            - '%core.table_prefix%'
    anavaro.zebraenhance.notifyhelper:
        class: anavaro\zebraenhance\controller\notifyhelper
        arguments:
            - '@service_container'
    anavaro.zebraenhance.notification.zebraadd:
        class: anavaro\zebraenhance\notification\zebraadd
        shared: false
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_config, ['@config']]
        tags:
            - { name: notification.type }
    
    anavaro.zebraenhance.notification.zebraconfirm:
        class: anavaro\zebraenhance\notification\zebraconfirm
        shared: false
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_config, ['@config']]
        tags:
            - { name: notification.type }